services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace_api_development
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    volumes:
      - .:/rails

volumes:
  postgres_data:
