default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: leohc
  password: "5521"
  pool: 5

development:
  <<: *default
  database: marketplace_api_development

test:
  <<: *default
  database: marketplace_api_test
